pandas

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dataset_vendas_80_linhas.csv")

In [6]:
df

,id,data,categoria,produto,preco,quantidade,desconto_percentual,cidade,canal,pagamento,cliente_id
0,1,2024-01-29,Eletronicos,Fone,120,3,0,Olinda,Online,Dinheiro,1047
1,2,2024-01-04,Eletronicos,Webcam,200,4,0,Recife,Online,Cartao,1032
2,3,2024-02-23,Eletronicos,Webcam,200,2,10,Olinda,Loja,Dinheiro,1017
3,4,2024-02-05,Eletronicos,Mouse,80,4,0,Olinda,Online,Pix,1006
4,5,2024-02-14,Eletronicos,Monitor,900,1,0,Cabo,Loja,Cartao,1046
...,...,...,...,...,...,...,...,...,...,...,...
75,76,2024-03-16,Casa,Copo,15,2,0,Olinda,Online,Dinheiro,1049
76,77,2024-01-06,Alimentos,Feijao,20,1,10,Jaboatao,Loja,Dinheiro,1023
77,78,2024-02-23,Eletronicos,Webcam,200,3,0,Paulista,Online,Pix,1023
78,79,2024-03-07,Casa,Liquidificador,220,4,0,Jaboatao,Loja,Pix,1027
79,80,2024-02-05,Alimentos,Pao,12,2,0,Paulista,Online,Pix,1036

In [13]:
regra_acima100 = df['preco'] >= 100
regra_cat = df['categoria'] == 'Eletronicos'
filtro_conjunto = regra_acima100 & regra_cat
tabela = df[filtro_conjunto]

In [14]:
tabela

,id,data,categoria,produto,preco,quantidade,desconto_percentual,cidade,canal,pagamento,cliente_id
0,1,2024-01-29,Eletronicos,Fone,120,3,0,Olinda,Online,Dinheiro,1047
1,2,2024-01-04,Eletronicos,Webcam,200,4,0,Recife,Online,Cartao,1032
2,3,2024-02-23,Eletronicos,Webcam,200,2,10,Olinda,Loja,Dinheiro,1017
4,5,2024-02-14,Eletronicos,Monitor,900,1,0,Cabo,Loja,Cartao,1046
7,8,2024-03-22,Eletronicos,Monitor,900,3,5,Jaboatao,Online,Pix,1022
15,16,2024-01-15,Eletronicos,Webcam,200,3,0,Jaboatao,Loja,Cartao,1029
16,17,2024-03-05,Eletronicos,Teclado,150,5,0,Recife,Loja,Dinheiro,1032
19,20,2024-03-09,Eletronicos,Fone,120,4,0,Olinda,Online,Dinheiro,1030
28,29,2024-01-07,Eletronicos,Monitor,900,5,0,Cabo,Online,Cartao,1048
32,33,2024-03-05,Eletronicos,Fone,120,5,5,Cabo,Online,Cartao,1032
43,44,2024-01-19,Eletronicos,Teclado,150,5,10,Paulista,Online,Cartao,1019
50,51,2024-02-14,Eletronicos,Fone,120,5,5,Jaboatao,Loja,Dinheiro,1032
51,52,2024-02-02,Eletronicos,Monitor,900,5,0,Recife,Loja,Cartao,1033
55,56,2024-02-25,Eletronicos,Teclado,150,3,0,Cabo,Loja,Pix,1028
66,67,2024-01-01,Eletronicos,Webcam,200,4,5,Jaboatao,Loja,Pix,1026
69,70,2024-02-29,Eletronicos,Fone,120,4,0,Olinda,Online,Pix,1024
71,72,2024-01-07,Eletronicos,Monitor,900,1,10,Jaboatao,Online,Dinheiro,1004
72,73,2024-01-03,Eletronicos,Fone,120,2,0,Cabo,Online,Cartao,1008
77,78,2024-02-23,Eletronicos,Webcam,200,3,0,Paulista,Online,Pix,1023